// Mocks generated by Mockito 5.4.4 from annotations
// in portal/test/src/apps/app_list_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:portal/src/apps/app.dart' as _i7;
import 'package:portal/src/apps/app_service.dart' as _i5;
import 'package:portal/src/stored/json.dart' as _i3;
import 'package:portal/src/stored/stored.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStored_1<T extends _i3.JSONSerializable> extends _i1.SmartFake
    implements _i4.Stored<T> {
  _FakeStored_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppService extends _i1.Mock implements _i5.AppService {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i6.Future<List<_i4.Stored<_i7.App>>> listApps({bool? showDeleted = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listApps,
          [],
          {#showDeleted: showDeleted},
        ),
        returnValue: _i6.Future<List<_i4.Stored<_i7.App>>>.value(
            <_i4.Stored<_i7.App>>[]),
        returnValueForMissingStub: _i6.Future<List<_i4.Stored<_i7.App>>>.value(
            <_i4.Stored<_i7.App>>[]),
      ) as _i6.Future<List<_i4.Stored<_i7.App>>>);

  @override
  _i6.Future<_i4.Stored<_i7.App>> addApp(String? name) => (super.noSuchMethod(
        Invocation.method(
          #addApp,
          [name],
        ),
        returnValue:
            _i6.Future<_i4.Stored<_i7.App>>.value(_FakeStored_1<_i7.App>(
          this,
          Invocation.method(
            #addApp,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.Stored<_i7.App>>.value(_FakeStored_1<_i7.App>(
          this,
          Invocation.method(
            #addApp,
            [name],
          ),
        )),
      ) as _i6.Future<_i4.Stored<_i7.App>>);

  @override
  _i6.Future<_i4.Stored<_i7.App>> getApp(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getApp,
          [name],
        ),
        returnValue:
            _i6.Future<_i4.Stored<_i7.App>>.value(_FakeStored_1<_i7.App>(
          this,
          Invocation.method(
            #getApp,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.Stored<_i7.App>>.value(_FakeStored_1<_i7.App>(
          this,
          Invocation.method(
            #getApp,
            [name],
          ),
        )),
      ) as _i6.Future<_i4.Stored<_i7.App>>);

  @override
  _i6.Future<void> setDisabled(
    String? name,
    bool? disabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDisabled,
          [
            name,
            disabled,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void handleErrorResponse(_i2.Response? response) => super.noSuchMethod(
        Invocation.method(
          #handleErrorResponse,
          [response],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> resetAPIKey(String? name) => (super.noSuchMethod(
        Invocation.method(
          #resetAPIKey,
          [name],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #resetAPIKey,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #resetAPIKey,
            [name],
          ),
        )),
      ) as _i6.Future<String>);
}
